/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Game */
        post: operations["create_game_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Play Action */
        post: operations["play_action_games__game_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/next-hand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deal Next Hand */
        post: operations["deal_next_hand_games__game_id__next_hand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionIn */
        ActionIn: {
            /**
             * Action
             * @description Índice del espacio de acciones (contrato v1).
             */
            action: number;
        };
        /** ActionResultOut */
        ActionResultOut: {
            game: components["schemas"]["GameOut"];
            /** New Events */
            new_events: components["schemas"]["EventOut"][];
        };
        /** AgentOut */
        AgentOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Description */
            description: string;
            /** Model Version */
            model_version: string | null;
        };
        /** BazaOut */
        BazaOut: {
            human: components["schemas"]["CardOut"] | null;
            bot: components["schemas"]["CardOut"] | null;
            /** Result */
            result: ("human" | "bot" | "parda") | null;
        };
        /** CardOut */
        CardOut: {
            /**
             * Id
             * @description Índice canónico 0..39.
             */
            id: number;
            /** Number */
            number: number;
            /**
             * Suit
             * @enum {string}
             */
            suit: "espada" | "basto" | "oro" | "copa";
            /** Label */
            label: string;
        };
        /** CreateGameIn */
        CreateGameIn: {
            /** Agent Id */
            agent_id: string;
            /** Seed */
            seed?: number | null;
        };
        /** EnvidoOut */
        EnvidoOut: {
            /** Calls */
            calls: string[];
            /** Pending */
            pending: boolean;
            /** Caller */
            caller: ("human" | "bot") | null;
            /** Resolved */
            resolved: boolean;
            /** Accepted */
            accepted: boolean;
            /** Human Value */
            human_value: number;
            /**
             * Bot Value
             * @description Solo si el envido fue querido.
             */
            bot_value: number | null;
            /** Winner */
            winner: ("human" | "bot") | null;
            /** Points */
            points: number;
        };
        /** EventOut */
        EventOut: {
            /** Seq */
            seq: number;
            /** Hand Number */
            hand_number: number;
            /**
             * Actor
             * @enum {string}
             */
            actor: "human" | "bot" | "system";
            /** Type */
            type: string;
            /** Action */
            action?: number | null;
            /** Action Name */
            action_name?: string | null;
            card?: components["schemas"]["CardOut"] | null;
            /**
             * Policy
             * @description Probabilidades por nombre de acción que usó el bot.
             */
            policy?: {
                [key: string]: number;
            } | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /** GameOut */
        GameOut: {
            /** Id */
            id: string;
            /** Agent Id */
            agent_id: string;
            /** Seed */
            seed: number;
            /**
             * Status
             * @enum {string}
             */
            status: "playing" | "hand_over" | "game_over";
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /** Target Score */
            target_score: number;
            /** Winner */
            winner: ("human" | "bot") | null;
            observation: components["schemas"]["ObservationOut"];
            /** Legal Actions */
            legal_actions: components["schemas"]["LegalActionOut"][];
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Contract Version */
            contract_version: string;
            /** Agents */
            agents: number;
        };
        /** LegalActionOut */
        LegalActionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Label */
            label: string;
        };
        /** ObservationOut */
        ObservationOut: {
            /** Hand Number */
            hand_number: number;
            /**
             * Mano
             * @enum {string}
             */
            mano: "human" | "bot";
            /** Turn */
            turn: ("human" | "bot") | null;
            /** Baza */
            baza: number;
            /** My Cards */
            my_cards: components["schemas"]["SlotOut"][];
            /** Bot Cards In Hand */
            bot_cards_in_hand: number;
            /** Bazas */
            bazas: components["schemas"]["BazaOut"][];
            truco: components["schemas"]["TrucoOut"];
            envido: components["schemas"]["EnvidoOut"];
            /** Hand Finished */
            hand_finished: boolean;
            /** Hand Winner */
            hand_winner: ("human" | "bot") | null;
            /** Hand Points */
            hand_points: {
                [key: string]: number;
            };
        };
        /** SlotOut */
        SlotOut: {
            /** Slot */
            slot: number;
            /** @description None si la carta ya se jugó. */
            card: components["schemas"]["CardOut"] | null;
        };
        /** TrucoOut */
        TrucoOut: {
            /**
             * Level
             * @description Valor aceptado de la mano: 1 a 4.
             */
            level: number;
            /** Pending */
            pending: boolean;
            /** Last Caller */
            last_caller: ("human" | "bot") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_agents_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"][];
                };
            };
        };
    };
    create_game_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    play_action_games__game_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deal_next_hand_games__game_id__next_hand_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
